### ISSUE TITLE
Its not clear the examples (and server) won't work with jsx

### ISSUE THREAD

**Issue by a-c-m** [asbjornenge/thinking-in-react#12]
It would be great to have jsx support, so you have the option to use it if you want.

**Comment by asbjornenge** [comment]
This is a good point and something that def. should be fixed. I think the best approach would be to **support jsx**. The tooling has improved a lot since I made the workshopper. I'll put it on my list, but it's quite a full so be my guest if you want to take a stap at it :smile:

**Comment by a-c-m** [comment]
Once I've finished the examples - I might :)

**Comment by asbjornenge** [comment]
:+1: :grin:

**Comment by asbjornenge** [comment]
Just release v2.0.0 that work with JSX and ES2015 via Babel :grin:
