### ISSUE TITLE
npm install doesn't add batch file or dependencies

### ISSUE THREAD

**Issue by C-F-K** [asbjornenge/thinking-in-react#16]
I'm on Win7; I recently updated node and npm by running the 4.x.x .msi, because the second exercise  of this workshopper required a newer version of node than I had. This caused several workshoppers to stop working (terminal recognized the commands, but nothing happened), so I uninstalled them and reinstalled this one.

Running `npm install -g thinking-in-react` doesn't create a batch file, such that trying to run `thinking-in-react` afterwards results in the error that it's not a recognized command etc.

Running `node C:\Users\CFK\AppData\Roaming\npm\node_modules\thinking-in-react\thinking-in-react.js` results in the node error that the `workshopper` module isn't found. Upon inspection, no `node_modules` folder is created on install, so this issue may be with npm itself. Other workshoppers install correctly, however.

**Comment by asbjornenge** [comment]
@C-F-K that is weird. I think this is either npm related or related to the workshopper version I'm using. If you want to try with another (more up-to-date) workshopper version (just replace in the package.json and try a re-install), that might be helpful.
