### ISSUE TITLE
Typo: Exercise 1 'completede'

### ISSUE THREAD

**Issue by brian-stovall** [asbjornenge/thinking-in-react#17]
The cool flashing reward for exercise 1 has a typo: 'completede'.

Will submit pull request momentarily...

**Comment by asbjornenge** [comment]
@brian-stovall hah, can't believe i missed that :see_no_evil: Thanks! :+1: :smile:

**Comment by asbjornenge** [comment]
@brian-stovall merged and released in 3.0.1 :smile: thanks again!

**Comment by brian-stovall** [comment]
Thanks for authoring a cool nodeschool module! Getting into react is a bit
tough for me, and it helped.

-brian

**Comment by asbjornenge** [comment]
@brian-stovall happy to hear it :smile:
